### ISSUE TITLE
SQLite Error: no such table: blog_data

### ISSUE THREAD

**Issue by Tset-Noitamotua** [stopspazzing/Sanic-Server-with-MDL-Blog-Template#4]
When I open the browser to http://127.0.0.1:8000 I see this error:

```
Error
('HY000', '[HY000] [SQLite]no such table: blog_data (1) (1) (SQLExecDirectW)')
```

I guess db must be prepared and populated first? Would you mind providing some noob-friendly detailed steps for that part, too? ;-)

Here is the full output in the terminal:
```bash
2017-05-13 14:57:56,651: INFO: Goin' Fast @ http://127.0.0.1:8000
Server successfully started!
2017-05-13 14:57:56,693: INFO: Starting worker [24940]
2017-05-13 14:58:10,324: ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 465, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "main.py", line 207, in index
    await cur.execute('SELECT * FROM blog_data;')
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
pyodbc.Error: ('HY000', '[HY000] [SQLite]no such table: blog_data (1) (1) (SQLExecDirectW)')

2017-05-13 14:58:10,327: ERROR: Exception occurred while handling uri: "http://127.0.0.1:8000/"
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 465, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "main.py", line 207, in index
    await cur.execute('SELECT * FROM blog_data;')
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
pyodbc.Error: ('HY000', '[HY000] [SQLite]no such table: blog_data (1) (1) (SQLExecDirectW)')

2017-05-13 14:58:10,487: ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 465, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "main.py", line 222, in post
    await cur.execute('SELECT * FROM blog_data WHERE post_name="{name}";')
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
pyodbc.Error: ('HY000', '[HY000] [SQLite]no such table: blog_data (1) (1) (SQLExecDirectW)')

2017-05-13 14:58:10,490: ERROR: Exception occurred while handling uri: "http://127.0.0.1:8000/favicon.ico"
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 465, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "main.py", line 222, in post
    await cur.execute('SELECT * FROM blog_data WHERE post_name="{name}";')
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
pyodbc.Error: ('HY000', '[HY000] [SQLite]no such table: blog_data (1) (1) (SQLExecDirectW)')

2017-05-13 14:59:10,006: ERROR: NoneType: None

2017-05-13 14:59:10,008: ERROR: NoneType: None
```

**Comment by stopspazzing** [comment]
Yes, the recent push I made kinda broke it... I am working to fix it, moved so much defaults to the first pages and they aren't creating those sql db as they should.

**Comment by stopspazzing** [comment]
Updated with working code. start pages are fixed. delete any .db files you had.
