### ISSUE TITLE
python run.py problem

### ISSUE THREAD

**Issue by echoboss** [stopspazzing/Sanic-Server-with-MDL-Blog-Template#5]
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from app import app
  File "/root/test/Sanic-MDL-Blog/app/__init__.py", line 5, in <module>
    from app import views
  File "/root/test/Sanic-MDL-Blog/app/views.py", line 110
    o.write(f'DB_URI = {repr(uri)}\n')
                                    ^
SyntaxError: invalid syntax

**Comment by stopspazzing** [comment]
What OS? sounds like something is missing. Never run into this problem.

**Comment by shellscope** [comment]
Have same problem (Debian, Python 3.5).
EDIT: I think I found the problem, f-strings were introduced in Python 3.6, which is not yet available in Debian's stable repo.

**Comment by stopspazzing** [comment]
Yeah @shellscope that is the issue. I wanted speed, used f strings for pure speed which removed support for Python 3.5. I compiled 3.6 from scratch to get it on debian. Do you think I should drop this or use checks to see if using 3.5 or 3.6? I did list the requirements as Python 3.6.. but if that many people cant use or test this then no point in keeping it 3.6=<.

**Comment by shellscope** [comment]
f-strings are indeed faster (https://cito.github.io/img/f-strings-1.png),
but it doesn't really matter in this case, because they are not heavily used.
I would downgrade to Python 3.5 to support more environments (and more users).
Just my 2 cents.
